### ISSUE TITLE
AttributeError: type object 'Environment' has no attribute 'Development'

### ISSUE THREAD

**Issue by marmata** [philliphall/plaid2qfx#11]
Hi! Just stumbled upon your script, which seems very useful to me as an user of Moneydance in EU, which doesn't have support for European banks yet. So I need to use qfx!
I created an account in Plaid, obtained the secrets, then run the scripts and I got this error:

```
Please provide your client API Secret: 
Traceback (most recent call last):
  File "c:\Users\Marco\Documents\src\plaid2qfx\plaid2qfx.py", line 795, in <module>
    main()
  File "c:\Users\Marco\Documents\src\plaid2qfx\plaid2qfx.py", line 136, in main
    link_name = link_account()
  File "c:\Users\Marco\Documents\src\plaid2qfx\plaid2qfx.py", line 277, in link_account
    response = get_client().link_token_create(request)
  File "c:\Users\Marco\Documents\src\plaid2qfx\plaid2qfx.py", line 99, in get_client
    host=plaid.Environment.Development, # Available environments are 'Production', 'Development', and 'Sandbox'
AttributeError: type object 'Environment' has no attribute 'Development'
```

Did I get anything wrong? Or API has changed in the meantime?
Thanks!

**Comment by philliphall** [comment]
I had to follow my own instructions to get this set up again, it has been a while 😊. I gave up on Quicken and moved on to Monarch Money.

Found an explanation Plaid Production APIs in June 2024 : r/fintech (reddit.com)<https://www.reddit.com/r/fintech/comments/1c8xxet/plaid_production_apis_in_june_2024/> that the Development environment has been deprecated. Sounds like today you need a production API key.

I’ll play with this for a bit and see if I can easily get it working again.

Glad to hear someone is interested in this project!

Thanks,
Phil

________________________________
From: marmata ***@***.***>
Sent: Saturday, September 14, 2024 12:29:10 PM
To: philliphall/plaid2qfx ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [philliphall/plaid2qfx] AttributeError: type object 'Environment' has no attribute 'Development' (Issue #11)


Hi! Just stumbled upon your script, which seems very useful to me as an user of Moneydance in EU, which doesn't have support for European banks yet. So I need to use qfx!
I created an account in Plaid, obtained the secrets, then run the scripts and I got this error:

Please provide your client API Secret:
Traceback (most recent call last):
  File "c:\Users\Marco\Documents\src\plaid2qfx\plaid2qfx.py", line 795, in <module>
    main()
  File "c:\Users\Marco\Documents\src\plaid2qfx\plaid2qfx.py", line 136, in main
    link_name = link_account()
  File "c:\Users\Marco\Documents\src\plaid2qfx\plaid2qfx.py", line 277, in link_account
    response = get_client().link_token_create(request)
  File "c:\Users\Marco\Documents\src\plaid2qfx\plaid2qfx.py", line 99, in get_client
    host=plaid.Environment.Development, # Available environments are 'Production', 'Development', and 'Sandbox'
AttributeError: type object 'Environment' has no attribute 'Development'


Did I get anything wrong? Or API has changed in the meantime?
Thanks!

**Comment by marmata** [comment]
Of course I'm interested! Great project if you ask me!

Simply ch anging that line to this let me continue:

`host=plaid.Environment.Production, # Available environments are 'Production', 'Development', and 'Sandbox'`

so the html is not created correctly. However when I try to link, I only get a list of US institutions (I'm in Italy). By further research it looks like only US and Canada are enabled by default, and I need to file a support ticket to request access to EU institutions. Perhaps it will work once I do that, I'll let you know!

**Comment by philliphall** [comment]
Updated the script on GitHub. You can re-sync or just change…
“host=plaid.Environment.Development,”

To…
“host=plaid.Environment.Production,”

I started requesting the Oauth permissions, but the questions get pretty invasive for personal use, so I tested with a non-Oauth institution (which is free for what they are calling “limited production” access). Seems to work okay, but let me know if you have any issues.

Make sure you are using your production API Secret when the script asks for it.

Let me know how it goes!

Phil

________________________________
From: Phillip Hall ***@***.***>
Sent: Saturday, September 14, 2024 12:58:27 PM
To: philliphall/plaid2qfx ***@***.***>; philliphall/plaid2qfx ***@***.***>
Cc: Subscribed ***@***.***>
Subject: RE: [philliphall/plaid2qfx] AttributeError: type object 'Environment' has no attribute 'Development' (Issue #11)


I had to follow my own instructions to get this set up again, it has been a while ??. I gave up on Quicken and moved on to Monarch Money.

Found an explanation Plaid Production APIs in June 2024 : r/fintech (reddit.com)<https://www.reddit.com/r/fintech/comments/1c8xxet/plaid_production_apis_in_june_2024/> that the Development environment has been deprecated. Sounds like today you need a production API key.



I’ll play with this for a bit and see if I can easily get it working again.



Glad to hear someone is interested in this project!



Thanks,

Phil



________________________________
From: marmata ***@***.***>
Sent: Saturday, September 14, 2024 12:29:10 PM
To: philliphall/plaid2qfx ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [philliphall/plaid2qfx] AttributeError: type object 'Environment' has no attribute 'Development' (Issue #11)


Hi! Just stumbled upon your script, which seems very useful to me as an user of Moneydance in EU, which doesn't have support for European banks yet. So I need to use qfx!
I created an account in Plaid, obtained the secrets, then run the scripts and I got this error:

Please provide your client API Secret:
Traceback (most recent call last):
  File "c:\Users\Marco\Documents\src\plaid2qfx\plaid2qfx.py", line 795, in <module>
    main()
  File "c:\Users\Marco\Documents\src\plaid2qfx\plaid2qfx.py", line 136, in main
    link_name = link_account()
  File "c:\Users\Marco\Documents\src\plaid2qfx\plaid2qfx.py", line 277, in link_account
    response = get_client().link_token_create(request)
  File "c:\Users\Marco\Documents\src\plaid2qfx\plaid2qfx.py", line 99, in get_client
    host=plaid.Environment.Development, # Available environments are 'Production', 'Development', and 'Sandbox'
AttributeError: type object 'Environment' has no attribute 'Development'


Did I get anything wrong? Or API has changed in the meantime?
Thanks!

**Comment by philliphall** [comment]
You beat me to it! Let me know how Italy access goes.

I’ll be moving my family to Italy (at least for the 3 months Italy will let me stay at a time) as soon as my house sells 😊.

Thanks,
Phil

________________________________
